#!/usr/bin/make -f
#
# MTS Makefile
#
.PHONY: all clean

SRCS    := mts.c exception.c event.c delay.c
#SRCS    += stackcheck.c exception_in.s

OBJS    := $(SRCS:.c=.o)
OBJS    := $(OBJS:.s=.o) # for exception_in.s

all:
	@echo "placeholder"
clean:
	@echo "placeholder"
