#!/usr/bin/make -f
#
# libfs Makefile
#
.PHONY: all clean

all:
	@echo "placeholder"
clean:
	@echo "placeholder"

# adapted from 5thMix's libfs/makefile
#SELECTOBJS = link_hd.o link_cd.o link_db.o link_cdd.o
#
#$(SELECTOBJS): select.c file.cnf
#	$(CC) $(OPTIONS) -D$(*F) $< -o $@
