#!/usr/bin/make -f
#
# libgcl Makefile
#
.PHONY: all clean

# link-order:
# libgcl.a(parse.o)     // parse.c
# libgcl.a(command.o)   // command.c
# libgcl.a(gcl_init.o)  // gcl_init.c
# libgcl.a(variable.o)  // variable.c
# libgcl.a(basic.o)     // basic.c
# libgcl.a(expr.o)      // expr.c

# ee-gcc 2.96-ee-001003-1
# CFLAGS = -O2 -G0 -fno-strict-aliasing

all:
	@echo "placeholder"
clean:
	@echo "placeholder"
